name: Portfolio-app

on:
  push:
    branches: [main]
  pull_request:
    branches: [dev, main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./pnpm-lock.yaml
      - run: npm install -g pnpm && pnpm install
      - run: pnpm run build

      - name: Get version from package.json
        id: get_version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: tag_name-${{ steps.get_version.outputs.version }}
          release_name: release_name-${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: true
